version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitness
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fitness"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  workout-service:
    build: ./workout-service
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy

  stat-service:
    build: ./stat-service
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  weekly-report-fn:
    build: ./weekly-report-fn
    environment:
      API_URL: http://stat-service:8083/resumen
      USERNAME: jose
    volumes:
      - ./weekly-report-fn/output:/app/output
    depends_on:
      - stat-service

networks:
  fitness-network:
    external: true
