global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'workout_service'
    static_configs:
      - targets: ['fitness-app-workout-service-1:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'simulator'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 5s


alerting:
  alertmanagers:
    - static_configs:
        - targets: []
