server:
  port: 8081 

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fitness
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
